version: '3'
services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - db
    volumes:
      - ./public:/app/public  
      - ./app.js:/app/app.js 
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargo
      POSTGRES_PORT: 5433
    ports:
      - "5433:5432"
    networks:
      - shared-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org  # Set your desired email
      PGADMIN_DEFAULT_PASSWORD: admin          # Set your desired password
    ports:
      - "5050:80"  # You can access pgAdmin on http://localhost:5050
    networks:
      - shared-network

networks:
  shared-network:
