name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cargo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v1

      - name: Build and Start Services
        run: docker-compose up -d

      - name: Wait for DB to be ready
        run: |
          until docker-compose exec db pg_isready -U postgres; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Shutdown Services
        run: docker-compose down
